Added a catch statement for NoClassDefFoundError
This error may be thrown by a URLClassLoader in some cases. It should not
be rethrown in this case since we want to try to load it from the other
configured classloaders.