Upgrading to Gradle 4.5
Following additional changes were done

* Ensured that versions in gradle and kobalt build
files are equal.
* Ensured that dependency scopes are the same across
both the build system files.
* Upgraded sonarqube plugin version to resolve 
NoClassDefFoundError due to gradle upgrade.